accounts:
  msg: Welcome to E-bank Account dev Application
  build-version: 2
  mail-details:
    hostName: dev-accounts@e-bank.com
    port: 9001
    from: dev-accounts@e-bank.com
    subject: Your Account details from e-banking dev env

  active-branches:
    - Atlanta
    - London
    - Washington