version: 3.8

services:

  configserver:
    image: possible/configserver
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - e-banking

  accounts:
    image: possible/account-service
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      -     e-banking
    depends_on:
      -     configserver
      -
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072

  card:
    image: possible/card-service
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - e-banking
    depends_on:
      - configserver
      -
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072

  loan:
    image: possible/loan-service
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - e-banking
    depends_on:
      - configserver
      -
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072