version: 3.8

services:

  configserver:
    image: possible/configserver
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - e-banking

  eurakaserver:
    image: possible/eureka-service
    mem_limit: 700m
    ports:
      - "8085:8085"
    networks:
      - e-banking
    depends_on:
      - configserver
      -
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072

  accounts:
    image: possible/account-service
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      -     e-banking
    depends_on:
      -     configserver
      -     eurakaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072
      EUREKA_CLIENT_SERVICE_DEFAULTZONE: http://eurekaserver:8085/eureka/

  card:
    image: possible/card-service
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - e-banking
    depends_on:
      -     configserver
      -     eurakaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072
      EUREKA_CLIENT_SERVICE_DEFAULTZONE: http://eurekaserver:8085/eureka/

  loan:
    image: possible/loan-service
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - e-banking
    depends_on:
      -     configserver
      -     eurakaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILE_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8072
      EUREKA_CLIENT_SERVICE_DEFAULTZONE: http://eurekaserver:8085/eureka/