# ===============================
# = DATA SOURCE
# ===============================
# configurations for the database connection
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/micro-bank?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
    username:  root
    password:  P@ssw0rd
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: create

      # Allows Hibernate to generate SQL optimized for a particular DBMS
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect