# ===============================
# = DATA SOURCE
# ===============================
# configurations for the database connection
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #    url:  jdbc:mysql://localhost:3306/micro-bank?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
#    username:  root
#    password:  P@ssw0rd
  jpa:
    show-sql:  true
    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#
#      # Allows Hibernate to generate SQL optimized for a particular DBMS
#    properties:
#      hibernate:
##        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8082