# ===============================
# = DATA SOURCE
# ===============================
# configurations for the database connection
spring:
  application:
    name: accounts
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #    url:  jdbc:mysql://localhost:3306/micro-bank?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
#    username:  root
#    password:  P@ssw0rd
  jpa:
    show-sql:  true
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8072/
#    hibernate:
#      ddl-auto: create
#
#      # Allows Hibernate to generate SQL optimized for a particular DBMS
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8082

#  registration with Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/


info:
  app:
    name: Accounts Microservice
    description: E-banking Account Application
    version: 1.0.0


endpoints:
  shutdown:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

#        Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      detailsForCustomerSupportApp:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberofCallsInHalfOpenState: 2
